version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=josesql
      - MYSQL_PASSWORD=mypassword
    ports: 
      - 3306:3306
    volumes: 
      - mysqldb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - "8080:80"

volumes:
  mysqldb:
    external: true